;; manifest.scm --- Guix Shell manifest file -*- mode: scheme; -*-
;;
;; SPDX-License-Identifier: GPL-3.0-or-later
;; Copyright © 2025 Urutau-Ltd <softwarelibre@urutau-ltd.org>
;;
;;   , _ ,      _    _            _                     _ _      _
;;  ( o o )    | |  | |          | |                   | | |    | |
;; /'` ' `'\   | |  | |_ __ _   _| |_ __ _ _   _ ______| | |_ __| |
;; |'''''''|   | |  | | '__| | | | __/ _` | | | |______| | __/ _` |
;; |\\'''//|   | |__| | |  | |_| | || (_| | |_| |      | | || (_| |
;;    """       \____/|_|   \__,_|\__\__,_|\__,_|      |_|\__\__,_|
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or (at
;; your option) any later version.
;;
;; This program is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <https://www.gnu.org/licenses/>.
(use-modules (guix packages)
             (guix download)
             (guix build-system copy)
             (guix utils)
             ((guix licenses)
              #:prefix license:)
             (guix gexp))

(define slsa-verifier
  (package
    (name "slsa-verfier")
    (version "2.7.1")
    (source
     (origin
       (method url-fetch)
       (uri (string-append
             "https://github.com/slsa-framework/slsa-verifier/releases/download/v"
             version "/slsa-verifier-linux-amd64"))
       (sha256
        (base32 "0f836panph6bc4pvvip20fgqc9sa68s1g3ppivl9ah89573vwvcl"))))
    (build-system copy-build-system)
    (arguments
     (list
      #:validate-runpath? #t
      #:install-plan
      #~'(("slsa-verifier-linux-amd64" "bin/slsa-verifier"))
      #:phases
      #~(modify-phases %standard-phases
          (add-after 'unpack 'fix-permissions
            (lambda _
              (invoke "chmod" "+x" "slsa-verifier-linux-amd64"))))))
    (home-page "https://github.com/slsa-framework/slsa-verifier")
    (supported-systems '("x86_64-linux"))
    (synopsis "Verify provenance from SLSA compliant builders")
    (description
     "slsa-verifier is a tool for verifying SLSA provenance that was generated by CI/CD builders. slsa-verifier verifies the provenance by verifying the cryptographic signatures on provenance to make sure it was created by the expected builder. It then verifies that various values such as the builder id, source code repository, ref (branch or tag) matches the expected values.")
    (license license:asl2.0)))

(concatenate-manifests (list (specifications->manifest (list "go" "gopls"))
                             (packages->manifest (list slsa-verifier))))
